// Fabric Loom configuration
loom {
    offline = true
}

// Maven publish configuration
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "https://maven.fabricmc.net/"
        }
    }
}
